### PR TITLE
Add generics in many more places within core, and a few small bug fixes (V2).

### PR DESCRIPTION
**Pull request by andrewdbate**
This PR also modifies the ModelCheck class to fix a bug that would incorrectly report that the language corresponding to one NFA was not a contained within the language corresponding to another NFA. Could you please review whether the changes that I made in commit 39c1fc0 seem correct to you?

### CODE REVIEW

**Comment by andrewdbate** [comment]
The last commit (6221d69) has fixed the problem with Travis CI. Could you please review commit 39c1fc0  before merging, as per my previous comment?

**Comment by abailly** [comment]
Thanks, will check that this evening.

**Comment by abailly** [comment]
I am very happy jautomata is interesting you enough to contribute to it. Out of curiosity, what are you using/planning to use it for?

**Comment by andrewdbate** [comment]
I am building a reasoner for a particular description logic (think theorem prover for a fragment of first-order logic). Part of the preprocessing step is to construct a NFA that recognizes the regular language encoded by certain clauses in the input. This NFA can then be reduced or determinised, and passed on for use in a calculus that derives logical entailments of a certain form. One application of this piece of work is a system that can be used for reasoning with ontologies written in the Web Ontology Language (which itself is based upon description logic).

**Comment by abailly** [comment]
Indeed ! That's really interesting, I am myself currently building a
startup in fintech and we want to develop a credit risk assessment engine
that would provide some deductions over a graph database, and I am looking
into how description logic could help us.

Le mercredi 1 avril 2015, Andrew D Bate notifications@github.com a écrit :

> I am building a reasoner for a particular description logic (think theorem
> prover for a fragment of first-order logic). Part of the preprocessing step
> is to construct a NFA that recognizes the regular language encoded by
> certain clauses in the input. This NFA can then be reduced or determinised,
> and passed on for use in a calculus that derives logical entailments of a
> certain form. One application of this piece of work is a system that can be
> used for reasoning with ontologies written in the Web Ontology Language
> (which itself is based upon description logic).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abailly/jautomata/pull/7#issuecomment-88489433.

## 

## 

Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Pull request merged**
