### PR TITLE
Add generics in many more places within core, and a few small bug fixes.

### PR DESCRIPTION
**Pull request by andrewdbate**

### CODE REVIEW

**Comment by abailly** [comment]
There is a problem with compilation: 

```
[ERROR] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[163,53] incompatible types: cannot infer type arguments for rationals.Automaton<>
    reason: inferred type does not conform to upper bound(s)
      inferred: T
      upper bound(s): rationals.Builder<L,rationals.Transition<L>,T>,rationals.Builder<L,capture#1 of ?,capture#2 of ?>
```

Any idea? I must say I am always puzzled by Java's generics...

**Comment by andrewdbate** [comment]
This is very strange... it is compiling just fine on my machine. (I'm using Java 8 Update 40 on Windows 7 x64, but I doubt that makes much difference.) I'll have to investigate today.

**Comment by abailly** [comment]
Here is the full stack trace with maven version:

```
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /usr/local/Cellar/maven/3.2.3/libexec
Java version: 1.8.0_20, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for oqube:jautomata-graph:jar:2.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ oqube:jautomata-graph:[unknown-version], /Users/arnaud/projects/jautomata/jautomata-graph/pom.xml, line 24, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for oqube:jautomata-ext:jar:2.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ oqube:jautomata-ext:[unknown-version], /Users/arnaud/projects/jautomata/jautomata-ext/pom.xml, line 22, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] JAutomata Library
[INFO] JAutomata Core
[INFO] JAutomata Graph interface
[INFO] JAutomata extensions
[INFO] JAutomata I/O
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JAutomata Library 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jautomata ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jautomata ---
[INFO] Installing /Users/arnaud/projects/jautomata/pom.xml to /Users/arnaud/.m2/repository/oqube/jautomata/2.0-SNAPSHOT/jautomata-2.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JAutomata Core 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jautomata-core ---
[INFO] Deleting /Users/arnaud/projects/jautomata/jautomata-core/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jautomata-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/arnaud/projects/jautomata/jautomata-core/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ jautomata-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 87 source files to /Users/arnaud/projects/jautomata/jautomata-core/target/classes
[INFO] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Morphism.java: Some input files additionally use unchecked or unsafe operations.
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] bootstrap class path not set in conjunction with -source 1.7
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[102,17] found raw type: rationals.StateFactory
  missing type arguments for generic class rationals.StateFactory<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[102,49] found raw type: rationals.DefaultStateFactory
  missing type arguments for generic class rationals.DefaultStateFactory<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[102,45] unchecked call to DefaultStateFactory(rationals.Automaton<L,Tr,T>) as a member of the raw type rationals.DefaultStateFactory
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[109,16] found raw type: rationals.StateFactory
  missing type arguments for generic class rationals.StateFactory<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[116,37] found raw type: rationals.StateFactory
  missing type arguments for generic class rationals.StateFactory<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[118,37] unchecked call to setAutomaton(rationals.Automaton<L,Tr,T>) as a member of the raw type rationals.StateFactory
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[198,26] found raw type: rationals.StateFactory
  missing type arguments for generic class rationals.StateFactory<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[199,54] found raw type: rationals.DefaultStateFactory
  missing type arguments for generic class rationals.DefaultStateFactory<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[199,50] unchecked call to DefaultStateFactory(rationals.Automaton<L,Tr,T>) as a member of the raw type rationals.DefaultStateFactory
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[201,47] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[202,49] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[203,50] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[290,56] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[338,53] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[603,48] found raw type: rationals.converters.toAscii
  missing type arguments for generic class rationals.converters.toAscii<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[603,67] unchecked call to toString(rationals.Automaton<L,Tr,T>) as a member of the raw type rationals.converters.toAscii
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[664,39] unchecked cast
  required: rationals.Automaton<L,Tr,T>.Key
  found:    java.lang.Object
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[746,53] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[796,53] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[821,50] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[874,54] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/StateMachine.java:[67,5] found raw type: rationals.StateFactory
  missing type arguments for generic class rationals.StateFactory<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/StateMachine.java:[74,26] found raw type: rationals.StateFactory
  missing type arguments for generic class rationals.StateFactory<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[42,28] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[43,5] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[49,22] unchecked call to step(java.util.Set<rationals.State>,L) as a member of the raw type rationals.Automaton
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[58,32] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[58,45] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[59,9] found raw type: rationals.Transition
  missing type arguments for generic class rationals.Transition<L>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[59,36] unchecked call to delta(java.util.Set<rationals.State>) as a member of the raw type rationals.Automaton
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[59,36] unchecked conversion
  required: java.util.Set<rationals.Transition>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/RandomWalk.java:[67,10] found raw type: rationals.Transition
  missing type arguments for generic class rationals.Transition<L>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/ToDFA.java:[56,38] redundant cast to java.util.Set<rationals.State>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/ToDFA.java:[58,44] redundant cast to rationals.State
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[32,48] found raw type: rationals.Synchronization
  missing type arguments for generic class rationals.Synchronization<L>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[47,31] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[47,38] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[47,12] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[48,9] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[48,21] found raw type: java.util.HashSet
  missing type arguments for generic class java.util.HashSet<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[48,17] unchecked call to HashSet(java.util.Collection<? extends E>) as a member of the raw type java.util.HashSet
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[49,20] unchecked call to retainAll(java.util.Collection<?>) as a member of the raw type java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[57,30] found raw type: java.util.Collection
  missing type arguments for generic class java.util.Collection<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[57,12] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[58,9] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[58,24] found raw type: java.util.HashSet
  missing type arguments for generic class java.util.HashSet<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[63,13] found raw type: java.util.Iterator
  missing type arguments for generic class java.util.Iterator<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[64,13] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[65,17] found raw type: java.util.Iterator
  missing type arguments for generic class java.util.Iterator<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[66,17] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[67,28] unchecked call to addAll(java.util.Collection<? extends E>) as a member of the raw type java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/DefaultSynchronization.java:[73,51] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[44,39] found raw type: rationals.transformations.UnaryTransformation
  missing type arguments for generic class rationals.transformations.UnaryTransformation<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[51,32] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[51,12] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[52,9] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[52,29] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[53,9] found raw type: java.util.Map
  missing type arguments for generic class java.util.Map<K,V>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[53,22] found raw type: java.util.HashMap
  missing type arguments for generic class java.util.HashMap<K,V>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[54,14] found raw type: java.util.Iterator
  missing type arguments for generic class java.util.Iterator<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[57,19] unchecked call to put(K,V) as a member of the raw type java.util.Map
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[60,14] found raw type: java.util.Iterator
  missing type arguments for generic class java.util.Iterator<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[61,13] found raw type: rationals.Transition
  missing type arguments for generic class rationals.Transition<L>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[63,39] found raw type: rationals.Transition
  missing type arguments for generic class rationals.Transition<L>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[63,35] unchecked call to Transition(rationals.State,L,rationals.State) as a member of the raw type rationals.Transition
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/PrefixClosure.java:[63,34] unchecked call to addTransition(rationals.Transition<L>) as a member of the raw type rationals.Automaton
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[50,9] found raw type: rationals.transformations.Mix
  missing type arguments for generic class rationals.transformations.Mix<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[50,23] found raw type: rationals.transformations.Mix
  missing type arguments for generic class rationals.transformations.Mix<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[50,31] found raw type: rationals.Synchronization
  missing type arguments for generic class rationals.Synchronization<L>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[55,39] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[55,46] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[55,20] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[56,56] found raw type: java.util.HashSet
  missing type arguments for generic class java.util.HashSet<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[56,51] unchecked method invocation: method unmodifiableSet in class java.util.Collections is applied to given types
  required: java.util.Set<? extends T>
  found: java.util.HashSet
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[56,52] unchecked conversion
  required: java.util.Set<? extends T>
  found:    java.util.HashSet
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[59,38] found raw type: java.util.Collection
  missing type arguments for generic class java.util.Collection<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[59,20] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[64,59] found raw type: java.util.Set
  missing type arguments for generic class java.util.Set<E>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[69,29] unchecked call to transform(rationals.Automaton<L,Tr,T>,rationals.Automaton<L,Tr,T>) as a member of the raw type rationals.transformations.Mix
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Shuffle.java:[69,29] unchecked conversion
  required: rationals.Automaton<L,Tr,T>
  found:    rationals.Automaton
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/RandomAutomaton.java:[133,26] redundant cast to rationals.State
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Reducer.java:[74,53] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Reducer.java:[75,53] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Reducer.java:[94,60] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/converters/analyzers/DefaultLexer.java:[34,38] found raw type: rationals.converters.analyzers.Lexer
  missing type arguments for generic class rationals.converters.analyzers.Lexer<L>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/converters/ToRExpression.java:[51,18] found raw type: rationals.properties.isNormalized
  missing type arguments for generic class rationals.properties.isNormalized<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/converters/ToRExpression.java:[51,37] unchecked call to test(rationals.Automaton<L,Tr,T>) as a member of the raw type rationals.properties.isNormalized
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/converters/ToRExpression.java:[109,36] redundant cast to java.lang.String
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/converters/ToRExpression.java:[127,14] redundant cast to java.lang.String
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/EpsilonTransitionRemover.java:[99,54] unchecked conversion
  required: java.util.Set<rationals.State>
  found:    java.util.Set
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Substitution.java:[83,91] unchecked cast
  required: rationals.Automaton<L,Tr,T>
  found:    java.lang.Object
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Substitution.java:[85,101] unchecked cast
  required: L
  found:    capture#3 of ?
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Morphism.java:[39,34] found raw type: rationals.transformations.UnaryTransformation
  missing type arguments for generic class rationals.transformations.UnaryTransformation<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Morphism.java:[41,13] found raw type: java.util.Map
  missing type arguments for generic class java.util.Map<K,V>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Morphism.java:[43,21] found raw type: java.util.Map
  missing type arguments for generic class java.util.Map<K,V>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Morphism.java:[50,32] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Morphism.java:[50,12] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Morphism.java:[51,9] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[WARNING] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/transformations/Morphism.java:[51,27] found raw type: rationals.Automaton
  missing type arguments for generic class rationals.Automaton<L,Tr,T>
[INFO] 100 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[163,53] incompatible types: cannot infer type arguments for rationals.Automaton<>
    reason: inferred type does not conform to upper bound(s)
      inferred: T
      upper bound(s): rationals.Builder<L,rationals.Transition<L>,T>,rationals.Builder<L,capture#1 of ?,capture#2 of ?>
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JAutomata Library .................................. SUCCESS [  0.297 s]
[INFO] JAutomata Core ..................................... FAILURE [  2.726 s]
[INFO] JAutomata Graph interface .......................... SKIPPED
[INFO] JAutomata extensions ............................... SKIPPED
[INFO] JAutomata I/O ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.299 s
[INFO] Finished at: 2015-03-31T10:53:59+02:00
[INFO] Final Memory: 15M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project jautomata-core: Compilation failure
[ERROR] /Users/arnaud/projects/jautomata/jautomata-core/src/main/java/rationals/Automaton.java:[163,53] incompatible types: cannot infer type arguments for rationals.Automaton<>
[ERROR] reason: inferred type does not conform to upper bound(s)
[ERROR] inferred: T
[ERROR] upper bound(s): rationals.Builder<L,rationals.Transition<L>,T>,rationals.Builder<L,capture#1 of ?,capture#2 of ?>
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jautomata-core
```

**Comment by abailly** [comment]
Anyhow, thanks a lot for the hard work!

**Comment by andrewdbate** [comment]
I have no idea why I can compile locally, but Travis CI refuses to compile. I'll close this PR and try again with a fix.

**Comment by abailly** [comment]
Might really be related to version of JVM, looks like some weird generics corner case... I will try with same version than Travis CI uses.

**Pull request closed without merging**
